version: "2"

services:
  test:
    build: ./test
    ports:
      - 9001:80
    environment:
      - "VIRTUAL_HOST=test.martinbryant.io"
      - "VIRTUAL_PORT=9001"
  beer-graphql:
    build: ./beer-graphql
    ports:
      - 5001:3001
    environment:
      - "VIRTUAL_HOST=beer-graphql.martinbryant.io"
      - "VIRTUAL_PORT=5001"
  jenkins:
    image: jenkins-docker
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/jenkins_home:/var/jenkins_home
    environment:
      - "VIRTUAL_HOST=jenkins.martinbryant.io"
      - "VIRTUAL_PORT=8080"
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
